require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BudgetsController do

  def mock_budget(stubs={})
    @mock_budget ||= mock_model(Budget, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all budgets as @budgets" do
      Budget.stub(:all) { [mock_budget] }
      get :index
      assigns(:budgets).should eq([mock_budget])
    end
  end

  describe "GET show" do
    it "assigns the requested budget as @budget" do
      Budget.stub(:find).with("37") { mock_budget }
      get :show, :id => "37"
      assigns(:budget).should be(mock_budget)
    end
  end

  describe "GET new" do
    it "assigns a new budget as @budget" do
      Budget.stub(:new) { mock_budget }
      get :new
      assigns(:budget).should be(mock_budget)
    end
  end

  describe "GET edit" do
    it "assigns the requested budget as @budget" do
      Budget.stub(:find).with("37") { mock_budget }
      get :edit, :id => "37"
      assigns(:budget).should be(mock_budget)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created budget as @budget" do
        Budget.stub(:new).with({'these' => 'params'}) { mock_budget(:save => true) }
        post :create, :budget => {'these' => 'params'}
        assigns(:budget).should be(mock_budget)
      end

      it "redirects to the created budget" do
        Budget.stub(:new) { mock_budget(:save => true) }
        post :create, :budget => {}
        response.should redirect_to(budget_url(mock_budget))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved budget as @budget" do
        Budget.stub(:new).with({'these' => 'params'}) { mock_budget(:save => false) }
        post :create, :budget => {'these' => 'params'}
        assigns(:budget).should be(mock_budget)
      end

      it "re-renders the 'new' template" do
        Budget.stub(:new) { mock_budget(:save => false) }
        post :create, :budget => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested budget" do
        Budget.stub(:find).with("37") { mock_budget }
        mock_budget.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :budget => {'these' => 'params'}
      end

      it "assigns the requested budget as @budget" do
        Budget.stub(:find) { mock_budget(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:budget).should be(mock_budget)
      end

      it "redirects to the budget" do
        Budget.stub(:find) { mock_budget(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(budget_url(mock_budget))
      end
    end

    describe "with invalid params" do
      it "assigns the budget as @budget" do
        Budget.stub(:find) { mock_budget(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:budget).should be(mock_budget)
      end

      it "re-renders the 'edit' template" do
        Budget.stub(:find) { mock_budget(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested budget" do
      Budget.stub(:find).with("37") { mock_budget }
      mock_budget.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the budgets list" do
      Budget.stub(:find) { mock_budget }
      delete :destroy, :id => "1"
      response.should redirect_to(budgets_url)
    end
  end

end
